apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spark-operator-access
rules:
  - apiGroups: ["sparkoperator.k8s.io"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: airflow-spark-access
subjects:
  - kind: ServiceAccount
    name: airflow-worker
    namespace: default
roleRef:
  kind: ClusterRole
  name: spark-operator-access
  apiGroup: rbac.authorization.k8s.io